bpftool: headerfile conflicts net/if.h and linux/if.h in ppc64
In ppc64, bpftool fails to build with redeclaration errors
due to conflicts as /usr/include/linux/if.h doesn't have support
for compatibility with /usr/include/net/if.h. Include headerfiles
locally built kernel headers using make headers_install.

```
  CC       map_perf_ring.o
  CC       xlated_dumper.o
  CC       btf.o
  CC       tracelog.o
  CC       perf.o
  CC       btf_dumper.o
  CC       net.o
In file included from net.c:12:0:
/usr/include/linux/if.h:71:2: error: redeclaration of enumerator ‘IFF_UP’
  IFF_UP    = 1<<0,  /* sysfs */
  ^
/usr/include/net/if.h:44:5: note: previous definition of ‘IFF_UP’ was here
     IFF_UP = 0x1,  /* Interface is up.  */
:::
:::
usr/include/net/if.h:75:5: note: previous definition of ‘IFF_PORTSEL’ was here
     IFF_PORTSEL = 0x2000, /* Can set media type.  */
     ^
/usr/include/linux/if.h:85:2: error: redeclaration of enumerator ‘IFF_AUTOMEDIA’
  IFF_AUTOMEDIA   = 1<<14, /* sysfs */
 * @IFF_SLAVE: slave of a load balancer. Volatile.
```

Signed-off-by: Balamuruhan S <bala24@linux.ibm.com>